name: Test Branch on Push
on:
  push:
    branches:
      - 'feat-auto-build'

jobs:
  build:
    name: Checkout and Test Code Base
    runs-on: ubuntu-latest
    steps:
      # Check out the current branch
      - uses: actions/checkout@main

      - name: Run build
        run: |
          npm prune
          npm install
